version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:chrome65-ff57
        environment:
          ## this enables colors in the output
          TERM: xterm
    parallelism: 1
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          key: v1-deps-{{ .Branch }}
          key: v1-deps

      - run: node --version
      - run: npm --version
      - run: npm ci

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache

      # Randomly pick 1 out of 5 LUIS Authoring Keys and set the BASH_ENV with it.
      - run: node .circleci/SetLuisAuthoringKey.js >> $BASH_ENV
      - run: node .circleci/RevealAuthoringKeys.js

      - run: npm run test
      - run: npm run cibuild

      # Clone the Samples BOT
      - run: git clone https://github.com/Microsoft/ConversationLearner-Samples -b develop ../cl-samples
      
      # Install and build sample Bot application
      - run: cd ../cl-samples && npm ci
      - run: cd ../cl-samples && npm run build

      # Run sample
      - run: 
          command: cd ../cl-samples && npm start
          background: true

      # Run UI
      - run: 
          command: npm start
          background: true

      # Run UI e2e tests
      #- run: npm run cypress -- run --browser chrome --spec "cypress/integration/(Regression).js" --record --key $CYPRESS_RECORD_KEY
      - run: npm run cypress -- run --spec "cypress/integration/(RunTestsFromList).spec.js" --record --key $CYPRESS_RECORD_KEY

      - store_artifacts:
          path: results
          
      - store_test_results:
          path: results
      
workflows:
  version: 2
  build:
    jobs:
      - build